# Site settings
title: xboard.dev
email: 
description: "Notes, ideas and experiments."
baseurl: ""
url: "http://www.xboard.dev"
twitter_username: xboard_
github_username:  xboard
bio_domain: "xboard.me"
permalink: /:title

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
theme: minima
plugins:
  - jekyll-feed
  - jekyll-jupyter-notebook
