# Site settings
title: xboard.dev
email: 
description: "Versão pt-br de algumas publicações que faço em https://xboard.dev"
baseurl: ""
url: "https://xboard.github.io"
twitter_username: xboard_
github_username:  xboard
bio_domain: "xboard.me"
permalink: /:title

# SEO settings
twitter:
  username: xboard_
  card: summary_large_image

social:
  name: Flavio Regis de Arruda
  links:
    - https://twitter.com/xbord_
    - https://www.linkedin.com/in/flavioarruda
    - https://github.com/xboard
    - https://bio.link/xboard
    - https://xboard.dev
# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
theme: minima
plugins:
  - jekyll-feed
  - jekyll-jupyter-notebook
  - jekyll-seo