# Site settings
title: xboard blog
email: 
description: "Notes, ideas and experiments."
baseurl: ""
url: "http://xboard.github.io"
twitter_username: fregis77
github_username:  xboard
permalink: /:title

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
theme: minima
plugins:
  - jekyll-feed
  - jekyll-jupyter-notebook
